config/routes.rb
Todos::Application.routes.draw do
  use_doorkeeper
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :todos

  namespace :api do
    namespace :v1 do
      resources :todos
    end
  end

end

app/models/todo.rb
class Todo < ActiveRecord::Base

  validates :description, :presence => true
  validates :priority, :numericality => {:allow_nil => true}

  belongs_to :user

  def to_json(options={})
    super(:only => [:id, :description, :due_date, :completed])
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todos

end

app/controllers/api/v1/api_controller.rb
module Api::V1
  class ApiController < ApplicationController
    def current_resource_owner
      User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
    end
    
    private
    
    def current_user
      @current_user ||= User.find(doorkeeper_token[:resource_owner_id])
    end

  end
end

app/controllers/api/v1/todos_controller.rb
require "#{Rails.root}/lib/todo_methods"

module Api::V1
  class TodosController < ApiController
    doorkeeper_for :all
    respond_to :json

    include TodoMethods    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || todos_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/todos_controller.rb
require "#{Rails.root}/lib/todo_methods"

class TodosController < ApplicationController

  before_filter :authenticate_user!
  respond_to :html, :json, :xml

  include TodoMethods

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_filter :authenticate_user!
  doorkeeper_for :all   

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/index.html.erb
<h3>Home</h3>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'My Todos', todos_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Todos" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Todos" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for(:todo, :html => { :role => 'form', :class => "form-horizontal col-md-5"}) do |f| %>
<div class="form-group">
  <%= f.label :description, :class => "control-label" %>
  <%= f.text_area :description, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :priority, :class => "control-label"  %>
  <%= f.select :priority, (1..5).to_a, {}, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :due_date, :class => "control-label"  %>
  <%= f.datetime_select :due_date, :class => "form-control" %>
</div>
<%= f.button :submit, :class => "btn btn-default" %>
<% end %>

app/views/todos/_list_element.html.erb
<tr>
  <td> <%= todo.priority %> </td>
  <td> <%= todo.description %> </td>
  <td> <%= todo.due_date.to_formatted_s(:short) %> </td>
  <td> <%= todo.completed? ? 'Complete' : 'Pending' %> </td>
  <td> 
    <%= link_to 'Edit', edit_todo_path(todo) %> | 
    <%= link_to 'Delete', todo_path(todo), :method => :delete %> 
  </td>
</tr>

app/views/todos/edit.html.erb
<h3>Edit Todo</h3>
<%= form_for(@todo, :method => :put, :html => { :role => 'form', :class => "col-md-5"}) do |f| %>
<div class="form-group">
  <%= f.label :description, :class => "control-label" %>
  <%= f.text_area :description, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :priority, :class => "control-label"  %>
  <%= f.select :priority, (1..5).to_a, {}, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :due_date, :class => "control-label"  %>
  <%= f.datetime_select :due_date, :class => "form-control" %>
</div>
<div class="checkbox">
  <label>
    <%= f.check_box :completed %> Completed
  </label>
</div>
<%= f.button :submit, :class => "btn btn-default" %>
<% end %>

app/views/todos/index.html.erb
<div class="container">

  <table class="table table-striped table-hover table-condensed">
    <tr>
      <th>Priority</th>
      <th>ToDo</th>
      <th>Due Date</th>
      <th>Status</th>
      <th></th>
    </tr>
    <%= render :partial => "list_element", :collection => @todos, :as => :todo %>
  </table>
  
  <h3>Add a todo</h3>
   <%= render :partial => "form" %>
</div>

app/views/todos/show.html.erb
<div id="todo">
  <%= todo.priority %> <%= todo.description %> <%= todo.due_date.to_formatted_s(:short) %>
</div>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br />
  <%= f.submit "Update" %>
<% end %>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<%= link_to 'Edit account', edit_user_path %>